# Generated by Django 5.0.7 on 2024-08-06 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppInfo',
            fields=[
                ('app_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('app_name', models.CharField(max_length=255)),
                ('min_installs', models.BigIntegerField()),
                ('score', models.FloatField()),
                ('ratings', models.BigIntegerField()),
                ('reviews_count', models.BigIntegerField()),
                ('updated', models.IntegerField()),
                ('version', models.CharField(max_length=255)),
                ('ad_supported', models.BooleanField()),
            ],
            options={
                'db_table': 'apps_info',
            },
        ),
    ]
