# Generated by Django 5.0.7 on 2024-08-06 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsInfoAPI', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='smallApp',
            fields=[
                ('app_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
        ),
    ]
