# Generated by Django 5.0.7 on 2024-08-13 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsInfoAPI', '0002_smallapp'),
    ]

    operations = [
        migrations.CreateModel(
            name='smallerApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(max_length=255)),
            ],
        ),
    ]
